### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: -2

### ISSUE THREAD

**Issue by tadtenacious** [databricks-industry-solutions/hls-payer-mrf-sparkstreaming#28]
Encountering an error attempting load an MRF file. The process used has worked for other MRF files. I confirmed the schema of the file is valid using the [cms schema validator tool](https://github.com/CMSgov/price-transparency-guide-validator). The example mrf file below is actually very small, MB range. 

```python
from time import sleep
import requests
import os

url = 'https://hioscar-cms-tic-us-east-1.s3.amazonaws.com/oscar/negotiated_rates/20230320/20230320-oscar-039-in-network.json'
file_name = '20230320-oscar-039-in-network.json'
file_location_python = os.path.join('/dbfs/tmp/',file_name)
file_location_dbfs = file_location_python.replace('/dbfs','dbfs:')
r = requests.get(url)
r.raise_for_status()
with open(file_location_python, 'wb') as f:
    f.write(r.content)

check_point_dir = 'dbfs:/tmp/mrf_checkpoint_test/'
target_table = f'default.raw'
dbutils.fs.rm(check_point_dir, True)
partition_bytes = 128 * 1024 * 1024
df = spark.readStream \
    .format("payer-mrf") \
    .option('payloadAsArray', 'true') \
    .option("buffersize", partition_bytes) \
    .option("maxFilesPerTrigger", 1) \
    .load(file_location_dbfs)

query = (
    df.writeStream
    .outputMode("append")
    .queryName("load-mrf-file")
    .option("checkpointLocation", check_point_dir)
    .table(target_table)
    )

wait_time = 10
sleep(wait_time)
msg, is_data_available, is_trigger_active = query.status.values()
while query.isActive:
    msg, is_data_available, is_trigger_active = query.status.values()
    if not is_data_available and not is_trigger_active and msg != "Initializing sources":
        query.stop()
    sleep(wait_time)
query.awaitTermination(wait_time)
```
The stack trace:
```
StreamingQueryException: Job aborted.
---------------------------------------------------------------------------
StreamingQueryException                   Traceback (most recent call last)
<command-4462385165050225> in <module>
     24         query.stop()
     25     sleep(wait_time)
---> 26 query.awaitTermination(wait_time)

/databricks/spark/python/pyspark/sql/streaming.py in awaitTermination(self, timeout)
     97             if not isinstance(timeout, (int, float)) or timeout < 0:
     98                 raise ValueError("timeout must be a positive integer or float. Got %s" % timeout)
---> 99             return self._jsq.awaitTermination(int(timeout * 1000))
    100         else:
    101             return self._jsq.awaitTermination()

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    121                 # Hide where the exception came from that shows a non-Pythonic
    122                 # JVM exception message.
--> 123                 raise converted from None
    124             else:
    125                 raise

StreamingQueryException: Job aborted.
=== Streaming Query ===
Identifier: load-mrf-file [id = 85089276-fb5a-48f4-913e-39d0e4c67368, runId = 22f65a25-a6d4-4549-a3af-eb801d5d7ace]
Current Committed Offsets: {com.databricks.labs.sparkstreaming.jsonmrf.JsonMRFSource@5a05afb1: -1}
Current Available Offsets: {com.databricks.labs.sparkstreaming.jsonmrf.JsonMRFSource@5a05afb1: 2}

Current State: ACTIVE
Thread State: RUNNABLE

Logical Plan:
com.databricks.labs.sparkstreaming.jsonmrf.JsonMRFSource@5a05afb1
```

Spark UI Failure Reason:
Job aborted due to stage failure: Task 2 in stage 40.0 failed 4 times, most recent failure: Lost task 2.3 in stage 40.0 (TID 89) (10.7.1.5 executor driver): java.lang.ArrayIndexOutOfBoundsException: -2
```
Job aborted due to stage failure: Task 2 in stage 40.0 failed 4 times, most recent failure: Lost task 2.3 in stage 40.0 (TID 89) (10.7.1.5 executor driver): java.lang.ArrayIndexOutOfBoundsException: -2
    at com.databricks.labs.sparkstreaming.jsonmrf.JsonMRFRDD.compute(JsonChunks.scala:52)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:380)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:344)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:380)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:344)
    at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
    at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
    at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
    at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
    at org.apache.spark.scheduler.Task.doRunTask(Task.scala:156)
    at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:125)
    at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
    at org.apache.spark.scheduler.Task.run(Task.scala:95)
    at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:832)
    at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1681)
    at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:835)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
    at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:690)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:750)

Driver stacktrace:
```

Cluster config:
```json
{
    "num_workers": 0,
    "cluster_name": "payer-mrf-10-4",
    "spark_version": "10.4.x-scala2.12",
    "spark_conf": {
        "spark.databricks.cluster.profile": "singleNode",
        "spark.master": "local[*, 4]",
        "spark.databricks.delta.preview.enabled": "true"
    },
    "azure_attributes": {
        "first_on_demand": 1,
        "availability": "ON_DEMAND_AZURE",
        "spot_bid_max_price": -1
    },
    "node_type_id": "Standard_D4_v2",
    "driver_node_type_id": "Standard_D4_v2",
    "ssh_public_keys": [],
    "custom_tags": {
        "ResourceClass": "SingleNode"
    },
    "spark_env_vars": {
        "PYSPARK_PYTHON": "/databricks/python3/bin/python3"
    },
    "autotermination_minutes": 20,
    "enable_elastic_disk": true,
    "cluster_source": "UI",
    "init_scripts": [],
    "single_user_name": "first.last@domain.com",
    "enable_local_disk_encryption": false,
    "data_security_mode": "SINGLE_USER",
    "runtime_engine": "STANDARD",
    "cluster_id": "0413-141057-d02wssjo"
}
```

**Comment by srijitcn** [comment]
@tadtenacious what version of the streaming source are you using? can you try using the latest version ([0.3.6](https://github.com/databricks-industry-solutions/hls-payer-mrf-sparkstreaming/releases/tag/0.3.6v) or [0.3.5](https://github.com/databricks-industry-solutions/hls-payer-mrf-sparkstreaming/releases/tag/0.3.5v))?

**Comment by tadtenacious** [comment]
@srijitcn I built the jar from main, which looks like 0.3.5. The link to 0.3.6 above, which databricks runtime is that tied to?

**Comment by tadtenacious** [comment]
I was able to get it working with 0.3.6! Should probably be on main to avoid confusion. Closing the issue.
